### ISSUE TITLE
Missing link

### ISSUE THREAD

**Issue by danilobecke** [serralvo/serralvo.github.io#5]
I tried to download your slides of the GIT course but the links weren't there :(
Fix it please :)
![screen shot 2017-04-26 at 6 06 48 pm](https://cloud.githubusercontent.com/assets/11629419/25457118/8a890028-2aab-11e7-9c9b-136882f7eb7b.png)

**Comment by serralvo** [comment]
https://speakerdeck.com/serralvo/mini-curso-de-git
